title: <p align = "center"> Durga Prasad Raghuraman </p>
logo: /assets/img/logo.png
description: 
<a href="https://www.linkedin.com/in/durga-prasad-raghuraman-38520133/">LinkedIn</a> 
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
